site_name: Moot Security Management - Documentation
site_url: https://docs.mootinc.com/
repo_url: https://github.com/Moot-Inc/Documentation
edit_uri: edit/main/docs/
site_description: Documentation for Moot Security Management
copyright: Copyright &copy; 2023 <a href="https://mootinc.com">Moot, Inc.</a> &nbsp;|&nbsp; <a href="#__consent">Change cookie settings</a>
theme:
  name: material
  logo: assets/Images/Moot Logo - Square White.svg
  favicon: assets/Images/Moot Logo - Square Blue.svg
  font: false
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to light theme
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - content.tabs.link
    - content.code.annotate
    - content.action.edit
    - content.code.copy
    - search.highlight
    - search.suggest
    - search.share
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
extra_css:
  - assets/Styles/common.css
plugins:
  - glightbox
  - search
extra:
  homepage: https://mootinc.com
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions: [accept, reject]
  generator: false
  analytics:
    provider: google
    property: G-8XGJ04G979
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://mootinc.com/contact" target="_blank" rel="noopener">feedback form</a>.
