site_name: Moot Products Documentation
site_url: https://docs.mootinc.com/
site_description: Documentation for Moot's various products
repo_url: https://github.com/Moot-Inc/Documentation
repo_name: Moot-Inc/Documentation
# edit_uri: edit/main/docs/
copyright: Copyright &copy; 2023 <a href="https://mootinc.com">Moot, Inc.</a> &nbsp;|&nbsp; <a href="#__consent">Change cookie settings</a>
theme:
  name: material
  custom_dir: overrides
  logo: /assets/Images/Moot Logo - Square White.svg
  favicon: /assets/Images/Moot Logo - Square Blue.svg
  font: false
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/lightbulb
        name: Switch to light theme
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.footer
    - content.tabs.link
    - content.code.annotate
  #  - content.action.edit
    - content.code.copy
    - search.highlight
    - search.suggest
    - search.share
markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.highlight:
      anchor_linenums: true
      pygments_lang_class: true
      line_spans: __span 
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
extra_css:
  - assets/Styles/common.css
plugins:
  - glightbox
  - search
extra:
  homepage: https://mootinc.com
  consent:
    cookies:
      analytics: Google Analytics
      github: GitHub
      clarity: Microsoft Clarity
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions: [accept, reject]
  generator: false
  analytics:
    provider: google
    property: G-8XGJ04G979
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve this page by
            using our <a href="https://mootinc.com/contact" target="_blank" rel="noopener">feedback form</a>.
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/moot-inc
      name: Moot's home on LinkedIn
    - icon: fontawesome/brands/telegram
      link: https://t.me/mootinc
      name: Moot's home on Telegram
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/@mootinc
      name: Moot's home on YouTube
    - icon: fontawesome/brands/github
      link: https://github.com/Moot-Inc/
      name: Moot's home on GitHub
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moot_inc
      name: Moot's home on Twitter
