site_name: SHI Orchestration Platform - Documentation
site_url: https://docs.shilab.com/
site_description: Documentation for the SHI orchestration platform
repo_url: https://github.com/Software-Hardware-Integration-Lab/Documentation
repo_name: Software-Hardware-Integration-Lab/Documentation
# edit_uri: edit/main/docs/
copyright: Copyright &copy; 2025 <a href="https://shi.com">SHI International Corp.</a> &nbsp;|&nbsp; <a href="#__consent">Change cookie settings</a>
theme:
  name: material
  custom_dir: overrides
  logo: /assets/Images/SHI Logo - Color.svg
  favicon: /assets/Images/Favicon.png
  font: false
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Automatic Theme Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light green
      toggle:
        icon: material/lightbulb-on-outline
        name: Light Theme Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light green
      toggle:
        icon: material/lightbulb-night
        name: Dark Theme Mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.expand
    - navigation.footer
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.suggest
    - search.share
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - toc:
      permalink: true
extra_css:
  - assets/Styles/common.css
plugins:
  - glightbox
  - privacy
  - search
extra:
  homepage: https://shilab.com
  consent:
    cookies:
      # analytics: Google Analytics
      github: GitHub
      clarity: Microsoft Clarity
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions: [accept, reject]
  generator: false
  # analytics:
  #   provider: google
  #   property: G-8XGJ04G979
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >-
  #           Thanks for your feedback! Help us improve this page by
  #           using sending us a note <a href="mailto:alex_kessel@shi.com" target="_blank" rel="noopener">to our feature PM</a>.
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/pages/SHI-International-Corp/164409770296612
      name: SHI's home on FaceBook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SHI_Intl
      name: SHI's home on X (Twitter)
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/shi-international-corp-
      name: SHI's home on Telegram
    - icon: fontawesome/solid/blog
      link: https://blog.shi.com/
      name: SHI's blog
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/shicorporation
      name: SHI's home on YouTube
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/shi_intl/
      name: SHI's home on Instagram
watch:
  - includes
