site_name: SHI Lab - Product Documentation
site_url: https://docs.shilab.com/
site_description: Documentation for the SHI orchestration platform
copyright: Copyright &copy; 2025 <a href="https://shi.com">SHI International Corp.</a> &nbsp;|&nbsp; <a href="#__consent">Change cookie settings</a>
theme:
  name: material
  custom_dir: overrides
  logo: /assets/Images/SHI Logo - Color.svg
  favicon: /assets/Images/Favicon.png
  font: false
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/theme-light-dark
        name: Automatic Theme Mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      accent: light green
      toggle:
        icon: material/lightbulb-on-outline
        name: Light Theme Mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      accent: light green
      toggle:
        icon: material/lightbulb-night
        name: Dark Theme Mode
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - navigation.footer
    - content.tabs.link
    - content.tooltips
    - content.code.annotate
    - content.code.copy
    - search.highlight
    - search.suggest
    - search.share
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - toc:
      permalink: true
extra_css:
  - assets/Styles/common.css
plugins:
  - glightbox
  - privacy
  - search
extra:
  homepage: https://shilab.com
  consent:
    cookies:
      # analytics: Google Analytics
      github: GitHub
      clarity: Microsoft Clarity
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions: [accept, reject]
  generator: false
  # analytics:
  #   provider: google
  #   property: G-8XGJ04G979
  #   feedback:
  #     title: Was this page helpful?
  #     ratings:
  #       - icon: material/emoticon-happy-outline
  #         name: This page was helpful
  #         data: 1
  #         note: >-
  #           Thanks for your feedback!
  #       - icon: material/emoticon-sad-outline
  #         name: This page could be improved
  #         data: 0
  #         note: >-
  #           Thanks for your feedback! Help us improve this page by
  #           using sending us a note <a href="mailto:alex_kessel@shi.com" target="_blank" rel="noopener">to our feature PM</a>.
  social:
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/pages/SHI-International-Corp/164409770296612
      name: SHI's home on FaceBook
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/SHI_Intl
      name: SHI's home on X (Twitter)
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/shi-international-corp-
      name: SHI's home on Telegram
    - icon: fontawesome/solid/blog
      link: https://blog.shi.com/
      name: SHI's blog
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/user/shicorporation
      name: SHI's home on YouTube
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/shi_intl/
      name: SHI's home on Instagram
watch:
  - includes
nav:
  - Home: index.md

  - SHIELD:
      - Overview: SHIELD/index.md
      - Prerequisites:
          - Overview: SHIELD/Prerequisites/index.md
          - Graph API Permissions: SHIELD/Prerequisites/Required-Graph-API-Permissions.md
      - Getting Started: SHIELD/Getting-Started.md
      - Usage Guide: SHIELD/Usage-Guide.md

      - Deploy:
          - Overview: SHIELD/Deploy/index.md
          - Deployment: SHIELD/Deploy/Deployment/index.md
          - Usage Guide: SHIELD/Deploy/Usage-Guide.md
          - Reference: SHIELD/Deploy/Reference/index.md
          - Troubleshooting: SHIELD/Deploy/Troubleshooting.md

      - Defend:
          - Overview: SHIELD/Defend/index.md
          - Prerequisites: SHIELD/Defend/Prerequisites.md
          - Deployment: SHIELD/Defend/Deployment.md
          - Usage Guide:
              - Overview: SHIELD/Defend/Usage-Guide/index.md
              - Devices:
                  - Commission Device: SHIELD/Defend/Usage-Guide/Device/0-Commission.md
                  - Decommission Device: SHIELD/Defend/Usage-Guide/Device/1-Decommission.md
                  - Assign Device: SHIELD/Defend/Usage-Guide/Device/2-Assign.md
                  - Unassign Device: SHIELD/Defend/Usage-Guide/Device/3-Unassign.md
              - Users:
                  - Commission User: SHIELD/Defend/Usage-Guide/User/Commission.md
                  - Decommission User: SHIELD/Defend/Usage-Guide/User/Decommission.md
          - Reference:
              - Overview: SHIELD/Defend/Reference/index.md
              - Hardware Selection: SHIELD/Defend/Reference/Hardware-Selection.md
              - Custom Apps:
                  - Corp VM:
                      - Index: SHIELD/Defend/Reference/Custom-Apps/Corp-VM/index.md
                      - Changelog: SHIELD/Defend/Reference/Custom-Apps/Corp-VM/Changelog.md
                  - Managed Installer Config:
                      - Index: SHIELD/Defend/Reference/Custom-Apps/ManagedInstaller-Config/index.md
                      - Changelog: SHIELD/Defend/Reference/Custom-Apps/ManagedInstaller-Config/Changelog.md
                  - Security Config:
                      - Index: SHIELD/Defend/Reference/Custom-Apps/Security-Config/index.md
                      - Changelog: SHIELD/Defend/Reference/Custom-Apps/Security-Config/Changelog.md
                      - File Changes: SHIELD/Defend/Reference/Custom-Apps/Security-Config/File-Changes.md
                      - Registry Changes: SHIELD/Defend/Reference/Custom-Apps/Security-Config/Registry-Changes.md
              - Diagrams:
                  - Device Commission: SHIELD/Defend/Reference/Diagrams/Device-Commission.md
                  - Device Decommission: SHIELD/Defend/Reference/Diagrams/Device-Decommission.md
                  - Device Assign: SHIELD/Defend/Reference/Diagrams/Device-Assign.md
                  - Device Unassign: SHIELD/Defend/Reference/Diagrams/Device-Unassign.md
                  - User Commission: SHIELD/Defend/Reference/Diagrams/User-Commission.md
                  - User Decommission: SHIELD/Defend/Reference/Diagrams/User-Decommission.md
              - Lifecycle:
                  - Privileged Device Workflows: SHIELD/Defend/Reference/Lifecycle/Privileged Device Workflows.md
          - Troubleshooting: SHIELD/Defend/Troubleshooting.md

      - Discover:
          - Overview: SHIELD/Discover/index.md
          - Deployment: SHIELD/Discover/Deployment/index.md
          - Usage Guide: SHIELD/Discover/Usage-Guide.md
          - Plugins:
              - Entra ID: SHIELD/Discover/Plugins/EntraID.md
              - Defender for Endpoint: SHIELD/Discover/Plugins/DefenderEndpoint.md
              - Defender for Identity: SHIELD/Discover/Plugins/DefenderIdentity.md
          - Supported Licenses: SHIELD/Discover/Supported-Licenses.md
          - Reference:
              - Overview: SHIELD/Discover/Reference/index.md
              - Reserved Principals: SHIELD/Discover/Reference/Reserved-Principals.md
              - Architecture:
                  - Process Flow: SHIELD/Discover/Reference/Architecture/Process-Flow.md
          - Troubleshooting: SHIELD/Discover/Troubleshooting.md

      - Reference:
          - Architecture:
              - Overview: SHIELD/Reference/Architecture/index.md
              - Threat Model: SHIELD/Reference/Architecture/Threat-Models/ISV-To-Customer.md
              - Review Template: SHIELD/Reference/Architecture/Review-Template.md
          - Development:
              - OpenAPI Spec: SHIELD/Reference/Development/OpenAPI.md
          - Settings:
              - Configure Managed Identity: SHIELD/Reference/Settings/Configure-Managed-Identity.md
              - Debug Mode: SHIELD/Reference/Settings/Debug-Mode.md
              - Environment Variables: SHIELD/Reference/Settings/Environmental-Variables-Reference.md
          - Uninstall: SHIELD/Reference/Uninstall.md

  - Data Gateway:
      - Overview: Data-Gateway/index.md
      - Deployment:
          - Overview: Data-Gateway/Deployment/index.md
      - Usage Guide: Data-Gateway/Usage-Guide/index.md
      - Architecture:
          - Overview: Data-Gateway/Architecture/index.md
          - Infrastructure: Data-Gateway/Architecture/Infrastructure.md
      - Reference:
          - Overview: Data-Gateway/Reference/index.md
      - Troubleshooting: Data-Gateway/Troubleshooting.md
