# Human friendly display name for this workflow
name: Build - Static Assets

# Event listeners for when the job should start execution
on:
    # Enable this workflow to be called by other workflows (reuseable workflow)
    workflow_call:

    # Allow this workflow to be triggered manually from the Actions tab
    workflow_dispatch:

# List of execution sandboxes that
jobs:
    # Unique identifier for the job, used for referencing in other jobs and steps
    Build_Docs:
        # Human friendly display name for the job
        name: Compile Static HTML

        # Operating system that the job will run on
        runs-on: ubuntu-latest

        # Sets permissions of the github token to allow for attestation generation, cloning the repo and OIDC auth
        permissions:
            attestations: write
            contents: read
            id-token: write

        # Set of actions to perform for this execution sandbox
        steps:
            # Download the markdown and supporting files
            - name: Checkout Files from Repo
              uses: actions/checkout@v6

            # Upload a copy of the static pages
            - name: Setup Python
              uses: actions/setup-python@v7
              with:
                python-version: "3.13"

            # Installs the python build dependencies for generating a static site
            - name: Install Build Dependencies
              run: pip install -r requirements.txt

            # Build the static HTML content based on the markdown
            - name: Build Static Content
              run: zensical build

            # Create a ZIP archive of the compiled documentation
            - name: ZIP up Compiled UI Files
              working-directory: site
              run: zip -r -9 ../docs.zip .

            # Create an attestation for the documentation artifact
            - name: Attest Documentation Artifact
              uses: actions/attest@v4
              with:
                  subject-path: docs.zip

            # Upload the compiled HTML as an artifact for future consumption
            - name: Upload a Build Artifact
              uses: actions/upload-artifact@v7
              with:
                  name: Documentation
                  if-no-files-found: error
                  path: docs.zip
